### ISSUE TITLE
Main method is not in API!!!!

### ISSUE THREAD

**Issue by nlnrose** [JHunterHobbs/Resource-Locking-Device#3]
Sorry to nit pick but I know he will fail us if we include public methods not in the api. We can create private method but a public method is not what we want. I'll fix this on my version. Also the problem is supposed to be solved in the method unlock. This is the implementation matching the required api (see below). http://jodypaul.com/cs/sweprin/deviceProj/api/FourBitTwoDisclosureDeviceUnlocker.html
[FourBitTwoDisclosureDeviceUnlocker.zip](https://github.com/JHunterHobbs/Resource-Locking-Device/files/1297437/FourBitTwoDisclosureDeviceUnlocker.zip)

**Comment by JHunterHobbs** [comment]
great. thanks for the review and ill get working on the issues!

**Comment by nlnrose** [comment]
the zip file contains the fix. I ran the below test. ps I am running a proxy server and apparantly git doesn't like that. I'll need to set up something that can get behind that so I can commit. in the mean time if you wouldn't mind doing it. Sorry.

PS: Heres the test code. It runs through and each run through results in a positive result 1000 times.

import static org.junit.Assert.*;
import org.junit.Test;

public class FourBitTwoDisclosureTest {

    @Test
    public void test() {
        for(int i = 0; i < 1000; i ++){
            assertTrue(FourBitTwoDisclosureDeviceUnlocker.unlock(new Device()));
        }
    }
}

**Comment by JHunterHobbs** [comment]
i just updated the code in the 4b2du class

**Comment by nlnrose** [comment]
you are awesome :)

**Comment by JHunterHobbs** [comment]
review and close this issue if it looks good. thanks.

**Comment by nlnrose** [comment]
The issue has been fixed and the method names have been updated to be more accurate.
